name: Publish to NPM

on:
  push:
    tags:
      # major.minor.patch - required
      # -tag.build - optional
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: get-package
        run: |
          echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
          echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/} | grep -oP '(?<=\d\.\d\.\d-)\w+' || echo 'latest')"
        shell: bash

      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Check version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [[ "${{steps.get-package.outputs.version}}" != "${PACKAGE_VERSION}" ]]; then
            echo "Tag version ${{steps.get-package.outputs.version}} does not match package version ${PACKAGE_VERSION}."
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: |
          npm publish --access=public --tag=${{ steps.get-package.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
