name: Publish to NPM

on:
  push:
    tags:
      # v means this is a version tag
      - '*-v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: get-package
        run: |
          FULL_TAG=${GITHUB_REF#refs/tags/}
          PACKAGE_NAME=$(echo $FULL_TAG | cut -d- -f1)
          ALLOWED_PACKAGES=("cdn" "npm")
          if [[ " ${ALLOWED_PACKAGES[@]} " =~ " ${PACKAGE_NAME} " ]]; then
            echo "::set-output name=package::${PACKAGE_NAME}"
            echo "::set-output name=version::$(echo $FULL_TAG | cut -d- -f2-)"
            echo "::set-output name=tag::$(echo $FULL_TAG | grep -oP '(?<=\d\.\d\.\d-)\w+' || echo 'latest')"
          else
            echo "Invalid package name ${PACKAGE_NAME}."
            exit 1
          fi
        shell: bash

      - uses: actions/checkout@v4

      - name: Check version
        run: |
          PACKAGE_VERSION=$(node -p "require('./packages/${${{steps.get-package.outputs.package}}}/package.json').version")
          if [[ "${{steps.get-package.outputs.version}}" != "v${PACKAGE_VERSION}" ]]; then
            echo "Tag version ${{steps.get-package.outputs.version}} does not match package version ${PACKAGE_VERSION}."
            exit 1
          fi

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: |
          npm publish --access=public --tag=${{ steps.get-package.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
