name: Check pull-request
on: [pull_request]

jobs:
  check-app:
    name: Check App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10
      - run: npm ci

      - name: Check lint
        run: npm run lint --workspaces

      - name: Check types
        run: npm run check-types --workspaces
